### ISSUE TITLE
Support latest ECS platform

### ISSUE THREAD

**Issue by mwkaufman** [rearc/quest#22]
Platform 1.3.0 report "Congratulations! You are running in a Docker container" correctly, but latest/1.4.0 platform report incorrectly that the application is not containerized.

**Comment by ramblingbiped** [comment]
I deployed a containerized version of the quest application to ECS Fargate this morning and can confirm this behavior persists.

![image](https://user-images.githubusercontent.com/11682383/120224927-f7092d00-c209-11eb-90d8-743c10000780.png)

ECS Platform Version 1.4.0

![image](https://user-images.githubusercontent.com/11682383/120225297-99c1ab80-c20a-11eb-9e59-9817f7e27ad9.png)

**Comment by jmorgancusick** [comment]
The reason the Docker check fails is because [AWS Fargate uses Containerd under the hood](https://aws.amazon.com/blogs/containers/under-the-hood-fargate-data-plane/), another industry-standard container runtime like Docker.
Both of these runtimes are OCI compatible, meaning one can still build and publish images from a Dockerfile when publishing to ECS Fargate.
Not sure how the binary to verify the app is containerized is written, but it should probably be enhanced to check for any OCI compatible container runtime (or at least Docker & Containerd)

**Comment by rahulsen** [comment]
fixed
